language: node_js
cache: npm

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script:
        - npm run build
        - npm run build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        on:
          branch: master
        github-token: $GITHUB_TOKEN
        local-dir: ./docs

stages:
  - test
  - name: build
    if: branch = master
