language: node_js
cache: npm

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script:
        - npm run build
        - npm run build-storybook
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: ./docs


stages:
  - test
  - name: build
    if: branch = master
  - name: deploy
    if: branch = master
